.PHONY: clean All

All:
	@echo "----------Building project:[ simulated - Debug ]----------"
	@"$(MAKE)" -f  "simulated.mk"
clean:
	@echo "----------Cleaning project:[ simulated - Debug ]----------"
	@"$(MAKE)" -f  "simulated.mk" clean
